pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview
      - status-success=DenysVuika.preact-translate
    actions:
      merge:
        method: merge
