name: Verify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build.lib
          yarn test
          yarn size
        env:
          CI: true
